version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/remote"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/robot"
    schedule:
      interval: "weekly"
