# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main" ]
    
  # For testing
  push:
    branches: [ "ci" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wizhi/setup-buf@v1
      with:
        version: '0.36.0'
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Installing protoc-gen-go
      run: |
        go get github.com/golang/protobuf/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
            - name: Build
    - name: Compiling proto files  
      run: |
        cd robot/proto
        protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative robot.proto
    - name: Build
      run: |
        cd robot
        go build -v ./...

    - name: Test
      run: |
        cd robot
        go test -v ./...
