name: go_lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1
        
    - uses: actions/checkout@v3
    - uses: wizhi/setup-buf@v1
      with:
        version: '0.36.0'
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        
    - name: Installing protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        
    - name: Compiling proto files  
      run: |
        cd robot/proto
        protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative robot.proto  

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: robot
        skip-pkg-cache: true
        skip-build-cache: true
